/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author nadil
 */
public class register extends javax.swing.JFrame {
Statement stmt;
     Connection con;
     String url = "jdbc:mysql://localhost:3306/hungrybits";

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JTextField();
        pw = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        landing = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email.setBackground(new java.awt.Color(255, 199, 0));
        email.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        email.setText("email@example.com");
        email.setBorder(null);
        email.setSelectionColor(new java.awt.Color(0, 51, 255));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 1260, 70));

        pw.setBackground(new java.awt.Color(255, 199, 0));
        pw.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        pw.setBorder(null);
        pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwActionPerformed(evt);
            }
        });
        getContentPane().add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 1250, 70));

        background.setForeground(new java.awt.Color(255, 199, 0));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/img/register (1).png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, -1));

        registerBtn.setText("register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 823, 380, 100));

        landing.setText("jButton1");
        landing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landingActionPerformed(evt);
            }
        });
        getContentPane().add(landing, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 43, -1, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void landingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landingActionPerformed
       // landing landing = new landing();
       // landing.setVisible (true);
        //this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_landingActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
String Email = email.getText();
        String password = String.valueOf(pw.getPassword()) ;
      

        JOptionPane.showMessageDialog(null, Email + "," + password );
        try {
            con = DriverManager.getConnection(url, "root", "");
            System.out.println("Database ditemukan");
            stmt = con.createStatement();
            String sql = "insert into user (Email, password) values('" + Email + "','" + password + "')";
             String sql1 = "insert into order_id (user_id) values('" + Email + "')";
            stmt.executeUpdate(sql);
             stmt.executeUpdate(sql1);

        } catch (SQLException ex) {
            System.err.println("SQLException :" + ex.getMessage());

        }


        landing Landing = new landing();
        Landing.setVisible (true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_registerBtnActionPerformed

    private void pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField email;
    private javax.swing.JButton landing;
    private javax.swing.JPasswordField pw;
    private javax.swing.JButton registerBtn;
    // End of variables declaration//GEN-END:variables
}
